### ISSUE TITLE
AudioPaLM: A Large Language Model That Can Speak and Listen

### ISSUE THREAD

**Issue by tutugarin** [tutugarin/SpeechGPT#1]
разобрать статью https://arxiv.org/abs/2306.12925

**Comment by nikitalotts** [comment]
## О чем статья?

В статье рассказывает про **AudioPaLM** — большую языковую модель, которая объединяет текстовые и аудио возможности для обработки и генерации речи. Главная цель разработки заключается в создании единой архитектуры для решения задач по работе с текстом и звуком. Важное уточнение: сама модель полностью не обучалась с нуля, а наследуется на большой языковой модели **PaLM** c использованием техник модели **AudioLM** при генерации звука.

## Какие задачи решает модель?

Модель предназначена для выполнения нескольких типов задач, а именно:

1. **Автоматическое распознавание речи (ASR)**: преобразование речи в текст.
2. **Автоматический перевод речи в текст (AST)**: перевод аудио на одном языке в текст на другом языке. 
3. **Перевод речи в другую речь (S2ST)**: перевод речи с одного языка на другой 
4. **Текст в речь (TTS)**: генерирация аудио из текста
5. **Машинный перевод (MT)**: перевод текста с одного языка на другой.

## Как решают задачи?

![Схема работы](https://everydayseries.com/content/images/2023/06/Untitled--1200---648-px---4-.png)

Если в кратце, то авторы представляют единую архитектуру для решения этих задач, основная идея которой состоит в том, что:

1) Вместо только текстовых токенов, как в LLM, теперь еще используются аудиотокены, которые соединяются вместе с текстовыми токенами и все это на вход подается трансформеру-декодеру. 
2) Декодер зависимости от задачи(ASR, AST, MT) либо сразу вернет текст, либо сначала возвращает "семантические токены" (это некоторые сжатые представляения аудиоданных, которые отвечают за представление смысла речи на уровне фонетики, синтаксиса и семантики), которые затем превращаются в акустические токены (они предоставляют информацию о том, как должна звучать речь).
3) Акустически токены преобразуются в звуковые волны с помощью моделей SoundStream или AudioLM и на выходе получается аудио файл.

Более подродно распишу как работает модель в конце текста, чтобы не занимать тут много места.

## Какие выводы?

Стоит сказать, что в статье достаточно много тестов и сравнений, и где-то модель была лучше всех предыдущих, где-то нет, но в среднем, модель почти всегда показывала одни из лучших результатов (зачастую самые лучшие). Ссылаясь на саму статью, "Top level results of this paper" можно видеть ниже, как видно почти во всем модель обошла предшественников*. 

| Модель                            | CoVoST2 AST BLEU ↑ | CVSS S2ST BLEU ↑ | VoxPopuli ASR WER ↓ |
|-----------------------------------|---------------------|-------------------|----------------------|
| Whisper Large-v2 1.5B [Radford et al., 2022]  | 29.1                | -                 | 13.6                 |
| mSLAM-CTC 2B [Bapna et al., 2022]             | 25.2                | -                 | 9.1                  |
| MAESTRO 600M [Chen et al., 2022c]             | 25.2                | -                 | 8.1                  |
| USM-M [Zhang et al., 2023a]                   | 30.7                | -                 | -                    |
| **AudioPaLM 8B AST (ours)**                    | **35.4**           | -                 | **11.1**             |
| **AudioPaLM 8B S2ST (ours)**                   | -                   | **36.2**          | -                    |
| **AudioPaLM-2 8B AST (ours)**                  | **37.8**           | -                 | **9.8**              |
| **AudioPaLM-2 8B cascaded ASR + translation (ours)** | -               | -                 | **9.8**              |

*эти данные были валидны на момент выхода статьи (22 июня 2023), сейчас возможно результаты другие.

## На чем обучались?

В статье упоминаются несколько наборов данных:

1. **CoVoST2**:.
   - Используется для автоматического перевода речи в текст (AST).
   - **В статье устаревшая информация: на данный момент уже есть аудио, переведенное в текст на 21 языке, включая русский.** 
   - Ссылка: https://github.com/facebookresearch/covost

2. **VoxPopuli**:
   - Включает речи из Европейского парламента и их транскрипции, используемые для задач ASR и S2ST.
   - **Отсутствует русский язык**

3. **Common Voice**:
   - Крупный мультиязычный набор данных, созданный пользователями, содержащий записи речи и соответствующий текст.
   - **Множество языков, в т.ч. русский**
   - Ссылка: https://commonvoice.mozilla.org/ru/datasets

4. **YouTube ASR**:
   - Непубличный датасет, размеченный с помощью USM-2B ASR для нужд YouTube.

5. **PaLM MT TTS**:
   - Непубличный датасет, созданный авторами статьи на основе других датасетов для задачи TTS.

## Есть ли какой нибудь код?

Нет, сама модель закрыта, попробовать и потестить ее нигде нельзя. Кода и весов нет.


## TL;DR Как работает модель

### 1. **Токенизация входных данных**
   На первом этапе входные данные, будь то текст или аудио, преобразуются в токены:
   - Текстовые данные токенизируются с использованием SentencePiece (метод, который разрезает текст на токены).
   - Аудиоданные сначала обрабатываются аудиомоделями (например, USM или w2v-BERT), которые извлекают векторные представления. Затем эти представления кодируются в дискретные аудиотокены с помощью кластеризации или других методов, таких как k-means.

   Input в модель — это последовательность токенов, представляющих текст или аудио.

### 2. **Входные эмбеддинги**
   После токенизации каждый токен преобразуется в векторное представление (эмбеддинг):
   - В случае текста это стандартные текстовые эмбеддинги.
   - Для аудио модель расширяет эту матрицу, добавляя новые строки для аудиотокенов.

### 3. **Декодер**
   Основная часть модели — это обычная декодерная архитектура трансформера.

   Вход в декодер — это последовательность токенов (текстовых или аудиотокенов), а выход — последовательность токенов, которые могут представлять либо текст, либо аудио.

### 4. **Выходные эмбеддинги и генерация**
   После обработки декодером полученная последовательность передается в выходную эмбеддинговую матрицу, которая преобразует векторы обратно в токены:
   - Если на выходе должны быть текстовые данные, то модель сразу генерирует текстовые токены.
   - Если задача требует генерации аудио, модель генерирует аудиотокены.

   Эти токены затем:
   - Либо преобразуются в текст (в случае текстовых задач).
   - Либо отправляются на следующую стадию генерации аудио (в случае задач синтеза речи).

### 5. **Генерация аудио (двухэтапная)**
   Для задач синтеза речи модель генерирует аудиотокены, которые затем преобразуются в аудиосигналы. Это происходит в два этапа:
   - **Этап 1 (семантические токены):** Модель сначала генерирует **семантические токены**, которые представляют содержание и основные характеристики речи.
   - **Этап 2 (акустические токены):** Затем эти семантические токены используются для генерации **акустических токенов**, которые кодируют детальные особенности звука (голос, интонация и т.д.). Для преобразования этих токенов в аудиосигнал используется система **SoundStream** или **AudioLM** для высококачественной реконструкции звука.

   Входом для генерации аудио является последовательность аудиотокенов, а выходом — звуковая волна, которая соответствует синтезированной речи, которая учитвает особенности говорящего.

**Comment by nikitalotts** [comment]
[common_voice_download.zip](https://github.com/user-attachments/files/17293476/common_voice_download.zip)
В анализе датасетов возникла ошибка: CoVoST2 действительно поддерживает русский язык, но он поддерживает только Russian → English, а English → Russian не поддерживает (таким образом, если мы использовать его в своей модели, то он нам не подходит, т.к. выходной язык нашей модели должен быть русский).
